"""empty message

Revision ID: 578dd8936227
Revises: 
Create Date: 2025-02-02 17:25:21.123141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578dd8936227'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('agency', sa.Integer(), nullable=False),
    sa.Column('account', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('channel', sa.Integer(), nullable=False),
    sa.Column('agency_orig', sa.Integer(), nullable=False),
    sa.Column('account_orig', sa.Integer(), nullable=False),
    sa.Column('agency_dest', sa.Integer(), nullable=False),
    sa.Column('account_dest', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('customer')
    # ### end Alembic commands ###
